### ISSUE TITLE
MC 1.10.2 - Mechanical Soldiers 1.0.3 - Guidebook Crash

### ISSUE THREAD

**Issue by Kyrnterra** [The-Fireplace/Mechanical-Soldiers#9]
Game crashes upon clicking the "Next" arrow in the section on building robots.

Minecraft Version: 1.10.2
Overlord Version: 2.3.7
Mechanical Soldiers Version: 1.0.3
GuideAPI Version: 1.10.2.2.0.3-46

Logs:

fml-cilent-latest: https://paste.ee/p/emJGx

Crash Log: https://paste.ee/p/qM8b1

```
// Don't be sad, have a hug! <3

Time: 8/3/17 12:30 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at net.minecraft.item.ItemStack.func_77952_i(ItemStack.java:245)
	at amerifrance.guideapi.page.reciperenderer.ShapedOreRecipeRenderer.draw(ShapedOreRecipeRenderer.java:48)
	at amerifrance.guideapi.page.PageIRecipe.draw(PageIRecipe.java:58)
	at amerifrance.guideapi.wrapper.PageWrapper.draw(PageWrapper.java:50)
	at amerifrance.guideapi.gui.GuiEntry.func_73863_a(GuiEntry.java:79)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382)
	at sun.reflect.GeneratedMethodAccessor43.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at Reflector.callVoid(Reflector.java:529)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1417)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)
```

**Comment by The-Fireplace** [comment]
This one isn't my fault, see TeamAmeriFrance/Guide-API#86

**Comment by The-Fireplace** [comment]
Not guide api's fault either. It looks like one of your mods adds a null OreDictionary value for gemDiamond. If I were you, I would try removing mods that add custom Diamonds, diamond substitutes, etc until you figure out which one it is.
